### ISSUE TITLE
Login not possible - returns error

### ISSUE THREAD

**Issue by mariobehling** [fossasia/foss.vn#1]
http://foss.vn/index.php?title=%C4%90%E1%BA%B7c_bi%E1%BB%87t:%C4%90%C4%83ng_nh%E1%BA%ADp&returnto=M%E1%BB%99t+s%E1%BB%91+l%C6%B0u+%C3%BD+v%E1%BB%81+c%C3%A1ch+vi%E1%BA%BFt+b%C3%A0i

Fatal error: Call to undefined method LoginForm::setContext() in /usr/www/users/opentek/fossvn/includes/specialpage/SpecialPageFactory.php on line 553

**Comment by namangoel1** [comment]
Is it fixed? I don't see that error anymore on the page you linked. Does it happen only when someone tries logging in?
