### ISSUE TITLE
Special Pages - return error

### ISSUE THREAD

**Issue by mariobehling** [fossasia/foss.vn#2]
http://foss.vn/index.php?title=%C4%90%E1%BA%B7c_bi%E1%BB%87t:Li%C3%AAn_k%E1%BA%BFt_%C4%91%E1%BA%BFn_%C4%91%C3%A2y/M%E1%BB%99t_s%E1%BB%91_l%C6%B0u_%C3%BD_v%E1%BB%81_c%C3%A1ch_vi%E1%BA%BFt_b%C3%A0i

Fatal error: Call to undefined method SpecialWhatLinksHere::setContext() in /usr/www/users/opentek/fossvn/includes/specialpage/SpecialPageFactory.php on line 553

**Comment by namangoel1** [comment]
Fixed, was due to the outdated Google Maps extension. Uncommented it from LocalSettings.php.
