### ISSUE TITLE
Adjust logo to correct area size

### ISSUE THREAD

**Issue by mariobehling** [fossasia/foss.vn#3]
Currently it is cut off at the left and right a bit.
![screenshot from 2015-09-01 03 27 23](https://cloud.githubusercontent.com/assets/1583873/9594274/686a90b6-5059-11e5-9cdf-a7fd77b276ab.png)

**Comment by hongquan** [comment]
Cannot access foss.vn

```
Fatal exception of type MWException
```

**Comment by tradzik** [comment]
Me either. Need to inspect.

niedz., 13.09.2015 o 15:52 użytkownik Nguyễn Hồng Quân <
notifications@github.com> napisał:
